/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BuildingDocumentRelation } from './building-document-relation';
// May contain unused imports in some cases
// @ts-ignore
import type { Document } from './document';
// May contain unused imports in some cases
// @ts-ignore
import type { NpgsqlPoint } from './npgsql-point';
// May contain unused imports in some cases
// @ts-ignore
import type { Organization } from './organization';

/**
 * 
 * @export
 * @interface Building
 */
export interface Building {
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    'buildingId'?: number;
    /**
     * 
     * @type {string}
     * @memberof Building
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Building
     */
    'address'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    'constructionYear'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    'totalArea'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    'floors'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Building
     */
    'description'?: string | null;
    /**
     * 
     * @type {NpgsqlPoint}
     * @memberof Building
     */
    'coordinates'?: NpgsqlPoint;
    /**
     * 
     * @type {string}
     * @memberof Building
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Building
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    'organizationId'?: number;
    /**
     * 
     * @type {Organization}
     * @memberof Building
     */
    'organization'?: Organization;
    /**
     * 
     * @type {Array<Document>}
     * @memberof Building
     */
    'documents'?: Array<Document> | null;
    /**
     * 
     * @type {Array<BuildingDocumentRelation>}
     * @memberof Building
     */
    'buildingDocumentRelations'?: Array<BuildingDocumentRelation> | null;
}

