/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Building } from './building';
// May contain unused imports in some cases
// @ts-ignore
import type { Document } from './document';

/**
 * 
 * @export
 * @interface BuildingDocumentRelation
 */
export interface BuildingDocumentRelation {
    /**
     * 
     * @type {number}
     * @memberof BuildingDocumentRelation
     */
    'buildingId'?: number;
    /**
     * 
     * @type {Building}
     * @memberof BuildingDocumentRelation
     */
    'building'?: Building;
    /**
     * 
     * @type {number}
     * @memberof BuildingDocumentRelation
     */
    'documentId'?: number;
    /**
     * 
     * @type {Document}
     * @memberof BuildingDocumentRelation
     */
    'document'?: Document;
    /**
     * 
     * @type {string}
     * @memberof BuildingDocumentRelation
     */
    'relationType'?: string | null;
}

