/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Document } from './document';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface DocumentPermission
 */
export interface DocumentPermission {
    /**
     * 
     * @type {number}
     * @memberof DocumentPermission
     */
    'documentId'?: number;
    /**
     * 
     * @type {Document}
     * @memberof DocumentPermission
     */
    'document'?: Document;
    /**
     * 
     * @type {number}
     * @memberof DocumentPermission
     */
    'userId'?: number;
    /**
     * 
     * @type {User}
     * @memberof DocumentPermission
     */
    'user'?: User;
    /**
     * 
     * @type {string}
     * @memberof DocumentPermission
     */
    'permissionType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentPermission
     */
    'grantedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentPermission
     */
    'grantedBy'?: number | null;
    /**
     * 
     * @type {User}
     * @memberof DocumentPermission
     */
    'grantedByUser'?: User;
}

