/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocumentTagRelation } from './document-tag-relation';

/**
 * 
 * @export
 * @interface DocumentTag
 */
export interface DocumentTag {
    /**
     * 
     * @type {number}
     * @memberof DocumentTag
     */
    'tagId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentTag
     */
    'name'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof DocumentTag
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {Array<DocumentTagRelation>}
     * @memberof DocumentTag
     */
    'documentTagRelations'?: Array<DocumentTagRelation> | null;
}

