/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Document } from './document';

/**
 * 
 * @export
 * @interface DocumentCategory
 */
export interface DocumentCategory {
    /**
     * 
     * @type {number}
     * @memberof DocumentCategory
     */
    'categoryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentCategory
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentCategory
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentCategory
     */
    'parentCategoryId'?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof DocumentCategory
     */
    'createdAt'?: Date;
    /**
     * 
     * @type {DocumentCategory}
     * @memberof DocumentCategory
     */
    'parentCategory'?: DocumentCategory;
    /**
     * 
     * @type {Array<DocumentCategory>}
     * @memberof DocumentCategory
     */
    'subCategories'?: Array<DocumentCategory> | null;
    /**
     * 
     * @type {Array<Document>}
     * @memberof DocumentCategory
     */
    'documents'?: Array<Document> | null;
}

