/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Building } from './building';
// May contain unused imports in some cases
// @ts-ignore
import type { BuildingDocumentRelation } from './building-document-relation';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentCategory } from './document-category';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentPermission } from './document-permission';
// May contain unused imports in some cases
// @ts-ignore
import type { DocumentTagRelation } from './document-tag-relation';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface Document
 */
export interface Document {
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    'documentId'?: number;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'filePath'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'fileType'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    'fileSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    'categoryId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    'buildingId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    'uploadedBy'?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Document
     */
    'uploadDate'?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Document
     */
    'lastModified'?: Date;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'version'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'status'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'description'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Document
     */
    'isPublic'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'metadata'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'fileName'?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Document
     */
    'uploadedAt'?: Date;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'groupId'?: string | null;
    /**
     * 
     * @type {Building}
     * @memberof Document
     */
    'building'?: Building;
    /**
     * 
     * @type {User}
     * @memberof Document
     */
    'uploader'?: User;
    /**
     * 
     * @type {DocumentCategory}
     * @memberof Document
     */
    'category'?: DocumentCategory;
    /**
     * 
     * @type {Array<DocumentTagRelation>}
     * @memberof Document
     */
    'documentTagRelations'?: Array<DocumentTagRelation> | null;
    /**
     * 
     * @type {Array<DocumentPermission>}
     * @memberof Document
     */
    'documentPermissions'?: Array<DocumentPermission> | null;
    /**
     * 
     * @type {Array<BuildingDocumentRelation>}
     * @memberof Document
     */
    'buildingDocumentRelations'?: Array<BuildingDocumentRelation> | null;
}

