services:
  temp-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: temp-backend
    ports:
      - "5001:5000"
    depends_on:
      - temp-postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=temp-postgres;Port=5432;Database=bitandbeam;Username=postgres;Password=postgres

  temp-postgres:
    image: postgres:17
    container_name: temp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitandbeam
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql

  temp-openapi-client:
    build:
      context: ./openapi-client
      dockerfile: Dockerfile
    container_name: temp-openapi_generator
    depends_on:
      temp-backend:
        condition: service_started
    volumes:
      - ./frontend/src/api:/local/generated-sdk
    environment:
      - SWAGGER_URL=http://temp-backend:5000
      - BACKEND_URL=http://amos.b-iq.net:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://temp-backend:5000/swagger/v1/swagger.json"]
      interval: 10s
      timeout: 5s
      retries: 5