services:
  backend:
    image: ghcr.io/amosproj/bitandbeam-backend:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      # - ollama
      - tika
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - CORS__AllowedOrigins=http://amos.b-iq.net,https://amos.b-iq.net
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=bitandbeam;Username=postgres;Password=postgres
      - Tika__ServerUrl=http://tika:9998
    volumes:
      - documentdata:/app/documents:rw
      - documents2data:/app/documents2:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - internal
      - web

  frontend:
    image: ghcr.io/amosproj/bitandbeam-frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      - API_URL=http://amos.b-iq.net:5000
    ports:
      - "80:80"
    networks:
      - web

  postgres:
    image: postgres:17
    container_name: bitandbeam_postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bitandbeam
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
      
  ollama:
    image: ghcr.io/amosproj/bitandbeam-ollama:latest
    container_name: ollama
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ollamadata:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - internal
    expose:
      - "11434"

  tika:
    image: apache/tika
    container_name: bitandbeam_tika
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/version"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
    expose:
      - "9998"

volumes:
  ollamadata:
  documentdata:
  documents2data:
  pgdata:

networks:
  internal:
    driver: bridge
  web:
    driver: bridge
