version: "3.8"

services:
  backend:
    image: ghcr.io/amosproj/bitandbeam-backend:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
      tika:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - CORS__AllowedOrigins=http://amos.b-iq.net,https://amos.b-iq.net
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=bitandbeam;Username=postgres;Password=postgres
      - Tika__ServerUrl=http://tika:9998
    volumes:
      - documentdata:/app/documents
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["dotnet", "Build.ING.dll"]

  frontend:
    image: ghcr.io/amosproj/bitandbeam-frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      - API_URL=http://amos.b-iq.net:5000
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    image: ghcr.io/amosproj/bitandbeam-ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"  # Ollama internal API
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || echo 'ok'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  postgres:
    image: postgres:17
    container_name: bitandbeam_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitandbeam
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  tika:
    build:
      context: ./tika
      dockerfile: Dockerfile
    #image: apache/tika
    container_name: bitandbeam_tika
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/version"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal
    expose:
      - "9998"

volumes:
  documentdata:
  pgdata:

networks:
  internal:
    driver: bridge
  web:
    driver: bridge
