services:      
  
  ollama:
    image: ghcr.io/amosproj/bitandbeam-ollama-gpu:latest
    container_name: ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "11434:11434"
