services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODEL=gemma3:1b     # <--- Bas yahan se change karna hai
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve & sleep 8 && ollama pull $OLLAMA_MODEL && wait"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - ollama
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=bitandbeam;Username=postgres;Password=postgres
      - Tika__ServerUrl=http://tika:9998
    volumes:
      - documentdata:/app/documents

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:5001

  openapi-client:
    build:
      context: ./openapi-client
      dockerfile: Dockerfile
    container_name: openapi_generator
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend/src/api:/local/generated-sdk
    environment:
      - SWAGGER_URL=http://backend:5000
      - BACKEND_URL=http://localhost:5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5000/swagger/v1/swagger.json"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17
    container_name: bitandbeam_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitandbeam

  tika:
    build:
      context: ./tika
      dockerfile: Dockerfile
    container_name: bitandbeam_tika
    restart: always
    ports:
      - "9998:9998"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/version"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama_data:
  documentdata:
  pgdata:
