server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  # Add explicit configuration for env.js
  location /assets/env.js {
      add_header Cache-Control "no-store, no-cache, must-revalidate";
      expires 0;
      try_files $uri =404;
  }

  location /assets/ {
      try_files $uri $uri/ =404;
  }

  location / {
      try_files $uri $uri/ /index.html;
      add_header Cache-Control "no-cache";
      # Add CORS headers
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
  }

  # Handle errors
  error_page 404 =200 /index.html;
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
      root /usr/share/nginx/html;
  }
}
