/* tslint:disable */
/* eslint-disable */
/**
 * BUILD.ING API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { OllamaRequest } from '../models';
/**
 * OllamaApi - axios parameter creator
 * @export
 */
export const OllamaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Sends prompt to Ollama backend and returns response with metadata.
         * @param {OllamaRequest} [ollamaRequest] Prompt and optional context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiOllamaAskPost: async (ollamaRequest?: OllamaRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Ollama/ask`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ollamaRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OllamaApi - functional programming interface
 * @export
 */
export const OllamaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OllamaApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Sends prompt to Ollama backend and returns response with metadata.
         * @param {OllamaRequest} [ollamaRequest] Prompt and optional context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiOllamaAskPost(ollamaRequest?: OllamaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiOllamaAskPost(ollamaRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OllamaApi.apiOllamaAskPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OllamaApi - factory interface
 * @export
 */
export const OllamaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OllamaApiFp(configuration)
    return {
        /**
         * 
         * @summary Sends prompt to Ollama backend and returns response with metadata.
         * @param {OllamaRequest} [ollamaRequest] Prompt and optional context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiOllamaAskPost(ollamaRequest?: OllamaRequest, options?: any): AxiosPromise<void> {
            return localVarFp.apiOllamaAskPost(ollamaRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OllamaApi - interface
 * @export
 * @interface OllamaApi
 */
export interface OllamaApiInterface {
    /**
     * 
     * @summary Sends prompt to Ollama backend and returns response with metadata.
     * @param {OllamaRequest} [ollamaRequest] Prompt and optional context
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OllamaApiInterface
     */
    apiOllamaAskPost(ollamaRequest?: OllamaRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * OllamaApi - object-oriented interface
 * @export
 * @class OllamaApi
 * @extends {BaseAPI}
 */
export class OllamaApi extends BaseAPI implements OllamaApiInterface {
    /**
     * 
     * @summary Sends prompt to Ollama backend and returns response with metadata.
     * @param {OllamaRequest} [ollamaRequest] Prompt and optional context
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OllamaApi
     */
    public apiOllamaAskPost(ollamaRequest?: OllamaRequest, options?: RawAxiosRequestConfig) {
        return OllamaApiFp(this.configuration).apiOllamaAskPost(ollamaRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

