using BUILD.ING.Data;
using BUILD.ING.Models;
using BUILD.ING.Swagger;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using Microsoft.OpenApi.Models;

using Serilog;                      // Added: Serilog namespace
using Serilog.Context;              // Added: for log context enrichment
using System.Diagnostics;          // Added: for Activity (trace IDs)

var builder = WebApplication.CreateBuilder(args);

// ---------- SERILOG CONFIGURATION ----------
// Configure Serilog as the logging provider for the application
Log.Logger = new LoggerConfiguration()
    .Enrich.FromLogContext()      // Enrich logs with contextual info (we'll add TraceId later)
    .WriteTo.Console(new Serilog.Formatting.Json.JsonFormatter()) // Log JSON to console
    .WriteTo.File(
        new Serilog.Formatting.Json.JsonFormatter(),
        "Logs/log-.json",         // Path with rolling files by date
        rollingInterval: RollingInterval.Day)
    .CreateLogger();

// Tell ASP.NET Core to use Serilog instead of the default logger
builder.Host.UseSerilog();

var conn = builder.Configuration.GetConnectionString("DefaultConnection");
Console.WriteLine($"⛳ Connection String: {conn ?? "null"}");

var MyAllowSpecificOrigins = "_myAllowSpecificOrigins";

builder.Services.AddCors(options =>
{
    options.AddPolicy(name: MyAllowSpecificOrigins,
                      policy =>
                      {
                          //policy.WithOrigins("http://localhost:8080") // <-- Angular dev server
                                policy.AllowAnyOrigin() // Allow requests from any origin - only for development
                                .AllowAnyHeader()
                                .AllowAnyMethod();
                      });
});



builder.Services.AddControllers();
// Add services to the container.
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection"))
           .EnableSensitiveDataLogging()
           .LogTo(Log.Information, LogLevel.Information));

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    options.IncludeXmlComments(xmlPath);

    options.SwaggerDoc("v1", new OpenApiInfo { Title = "BUILD.ING API", Version = "v1" });
    options.SchemaFilter<BuildingRequestExampleSchemaFilter>();

}); //load the comments from the .xml doc generated by the compiler


// Add health check service
builder.Services.AddHealthChecks();
builder.Services.AddHttpClient();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.Migrate(); //führt Migration beim Start automatisch aus
}

// ---------- MIDDLEWARE TO ADD TRACE ID TO LOG CONTEXT ----------
app.Use(async (context, next) =>
{
    // Check if incoming request already has a trace ID header
    const string traceIdHeaderName = "X-Correlation-ID";
    string traceId = context.Request.Headers.ContainsKey(traceIdHeaderName)
        ? context.Request.Headers[traceIdHeaderName].ToString()
        : Guid.NewGuid().ToString();

    // Add trace ID to response headers so clients can see it
    context.Response.OnStarting(() =>
    {
        context.Response.Headers[traceIdHeaderName] = traceId;
        return Task.CompletedTask;
    });
    // Push TraceId into Serilog’s LogContext so all logs within this request include it
    using (Serilog.Context.LogContext.PushProperty("TraceId", traceId))
    {
        await next.Invoke(); // Call the next middleware in the pipeline
    }
});

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors(MyAllowSpecificOrigins);

app.UseAuthorization();
app.UseHttpsRedirection();

app.MapControllers();

var summaries = new[]
{
    "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast")
.WithOpenApi();

//Adds health check endpoint that returns HTTP 200
app.MapHealthChecks("/healthz");

//Just to set a route at /
app.MapGet("/", () => "🚀 API is running! Visit /swagger , /weatherforecast or /healthz.");

// Ensure the documents folder exists
//app.UseStaticFiles(new StaticFileOptions
//{
//    FileProvider = new PhysicalFileProvider("/app/documents"),
//    RequestPath = "/documents"
//});


app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int) (TemperatureC / 0.5556);
}


